{% set name = "yaval" %}
{% set version = "0.0.1.post2" %}
{% set sha256 = "8870c04c0367aeea16ca72bbc5a1f43a0981bb4e96a75632dece9d65160d4145" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib
    - vispy
    - pyside2

test:
  imports:
    - yaval

about:
  home: https://github.com/csachs/yaval
  license: BSD-2-Clause
  license_family: BSD
  summary: 'yet another visualization abstraction layer'
  description: |
    yet another visualization abstraction layer
  doc_url: https://github.com/csachs/yaval
  dev_url: https://github.com/csachs/yaval

extra:
  recipe-maintainers:
    - csachs

