{% set name = "mycelyso-inspector" %}
{% set version = "1.0.0rc1" %}
{% set sha256 = "59861253cf2c8f179a6981a82fe2e277910066963fed3d59b6887bc18095483b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - scipy
    - matplotlib
    - mpld3
    - pandas
    - flask
    - networkx
    - purepng

test:
  imports:
    - mycelyso_inspector

about:
  home: https://github.com/modsim/mycelyso-inspector
  license: BSD-2-Clause
  license_family: BSD
  summary: 'mycelyso - MYCEelium anaLYsis SOftware Inspector'
  description: |
    MYCEelium anaLYsis SOftware, see https://github.com/modsim/mycelyso for details.
    This is the mycelyso-inspector component.

  doc_url: https://mycelyso.readthedocs.io
  dev_url: https://github.com/modsim/mycelyso

extra:
  recipe-maintainers:
    - csachs
