{% set name = "mycelyso-inspector" %}
{% set version = "1.0.0rc2" %}
{% set sha256 = "991ff2031eb69856bbd6f0ccb86f1a4a5af152e70e16f8b47a2b370317911bf1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - scipy
    - matplotlib
    - mpld3
    - pandas
    - flask
    - networkx
    - purepng

test:
  imports:
    - mycelyso_inspector

about:
  home: https://github.com/modsim/mycelyso-inspector
  license: BSD-2-Clause
  license_family: BSD
  summary: 'mycelyso - MYCEelium anaLYsis SOftware Inspector'
  description: |
    MYCEelium anaLYsis SOftware, see https://github.com/modsim/mycelyso for details.
    This is the mycelyso-inspector component.

  doc_url: https://mycelyso.readthedocs.io
  dev_url: https://github.com/modsim/mycelyso

extra:
  recipe-maintainers:
    - csachs
