{% set name = "keras_nvidia_statistics" %}
{% set version = "0.0.1dev4" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: 02fca4807ca768cd6488fc4a9aca00abfd7aa2f4
  git_url: https://github.com/csachs/keras-nvidia-statistics
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - py3nvml

test:
  imports:
    - keras_nvidia_statistics

about:
  home: https://github.com/csachs/keras-nvidia-statistics
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Generate device statistics (such as utilization, temperature, …) via a keras callback'
  description: |
    Generate device statistics (such as utilization, temperature, …) via a keras callback
    
  doc_url: https://github.com/csachs/keras-nvidia-statistics
  dev_url: https://github.com/csachs/keras-nvidia-statistics
  
extra:
  recipe-maintainers:
    - csachs

