{% set name = "imagej-tiff-meta" %}
{% set version = "0.0.1.dev3" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: 95c4141ef553527f3900b9986255ab451b15bd10
  git_url: https://github.com/csachs/imagej-tiff-meta
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - imagej_tiff_meta

about:
  home: https://github.com/csachs/imagej-tiff-meta
  license: BSD
  license_family: BSD
  summary: 'Experimental support to read and write overlay (ROI) information from ImageJ/Fiji TIFFs.'
  description: |
    Experimental support to read and write overlay (ROI) information from ImageJ/Fiji TIFFs.
  doc_url: https://github.com/csachs/imagej-tiff-meta
  dev_url: https://github.com/csachs/imagej-tiff-meta

extra:
  recipe-maintainers:
    - csachs

