{% set name = "mycelyso" %}
{% set version = "1.0.0rc5" %}
{% set sha256 = "aa62405c3e7fe377eb4bf99da0312fe4fcdda6619c8f7ed7a7fc5565961a23c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - scipy
    - matplotlib
    - nd2file
    - tifffile
    - scikit-image
    - networkx
    - pytables
    - numexpr
    - pandas
    - mfisp-boxdetection
    - molyso
    - tunable
    - tqdm

test:
  imports:
    - mycelyso

about:
  home: https://github.com/modsim/mycelyso
  license: BSD-2-Clause
  license_family: BSD
  summary: 'mycelyso - MYCEelium anaLYsis SOftware'
  description: |
    MYCEelium anaLYsis SOftware, see https://github.com/modsim/mycelyso for details.

  doc_url: https://mycelyso.readthedocs.io
  dev_url: https://github.com/modsim/mycelyso

extra:
  recipe-maintainers:
    - csachs

