{% set name = "tunable" %}
{% set version = "0.0.1.dev7" %}
{% set sha256 = "6bab7d941f2bfcd331c471556bd1dc587f13050c9f0e8172f3b0b2b8acfe389b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python
    - pip
    - flit-core
  run:
    - python
    - pyasn1
    - pyyaml

test:
  imports:
    - tunable

about:
  home: https://github.com/csachs/tunable
  license: MIT
  license_family: MIT
  summary: 'A little Python library to set/manage tunable (configuration) values'
  description: |
    A tiny library to support tunable parameters (think: configuration values) as they often occur in scientific analyses. A main aspect differing from many other config approaches is, that the tunables are defined as classes where needed throughout the source, with default value, type, optional documentation etc., which makes later access fast, IDE-supported (code completion) and prevents running it with "missing defaults" or misspelled keys leading to runtime errors.
  doc_url: https://github.com/csachs/tunable
  dev_url: https://github.com/csachs/tunable

extra:
  recipe-maintainers:
    - csachs
