{% set name = "pilyso-io" %}
{% set version = "0.0.1.dev1" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: 58cd191d6e8a65cbb65da7bb9d997ec0769a3420
  git_url: https://github.com/csachs/pilyso-io
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - tifffile
    - czifile
    - nd2file

test:
  imports:
    - pilyso_io.imagestack
    - pilyso_io.imagestack.readers

about:
  home: https://github.com/csachs/pilyso-io
  license: BSD-2-Clause
  license_family: BSD
  summary: 'Python Image anaLYsis SOftware IO part – abstracted bioimage access'
  description: |
    Python Image anaLYsis SOftware IO part – abstracted bioimage access
  doc_url: https://github.com/csachs/pilyso-io
  dev_url: https://github.com/csachs/pilyso-io

extra:
  recipe-maintainers:
    - csachs

