{% set name = "vispy-pyside2" %}
{% set version = "0.0.1.dev1" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: a48cc6abff743cfaaadf3c3c3c092d72e046dab5
  git_url: https://github.com/vispy/vispy
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - vispy

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_family: BSD
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'
  description: |
    VisPy is a high-performance interactive 2D/3D data visualization library.
  doc_url: http://vispy.org/
  dev_url: http://vispy.org/

extra:
  recipe-maintainers:
    - csachs

